name: docker-build-push

on:
  push:
    branches: [ "main" ]
    tags: [ "v*", "release-*" ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image name
        id: vars
        run: |
          REPO="${{ github.repository }}"
          echo "IMAGE=ghcr.io/${REPO,,}" >> $GITHUB_OUTPUT
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "TAG=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "TAG=${{ github.sha }}" >> $GITHUB_OUTPUT
          fi

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.vars.outputs.IMAGE }}:${{ steps.vars.outputs.TAG }}
          build-args: |
            SDK_REGISTRY=huggingface
            SDK_IMAGE=hfendpoints-sdk
            SDK_VERSION=v0.2.0-patched
          cache-from: type=gha
          cache-to: type=gha,mode=max

